### ISSUE TITLE
Broken Example Scripts

### ISSUE THREAD

**Issue by jmwright** [CadQuery/cadquery-contrib#12]
Any of the examples in the readme without images seen to be broken. This likely includes the extruder support from issue #3

**Comment by Jojain** [comment]
That's the problem with not having image at the beginning, it's not always easy to know what the script was supposed to create when it was working. 
I had try to solve the parametric enclosure script, by changing some of the parameters values the script render something but since I had no clue what it was supposed to be I left it broken

**Comment by jmwright** [comment]
I have fixed all of the examples except for the extruder support, which has its own issue.

**Comment by jmwright** [comment]
Note: The motorcycle handlebar remote enclosure had a fudge factor for the trapezoid shape that makes things a little weird and so the holes probably aren't placed as they were originally.
